CREATE TABLE sredstvo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    inventarni_broj NUMBER NOT NULL UNIQUE,

    naziv VARCHAR2(255) NOT NULL,
    opis VARCHAR2(1000) NOT NULL,

    datum_aktivacije DATE DEFAULT SYSDATE NOT NULL,

    status VARCHAR2(20) DEFAULT 'u izradi' NOT NULL,
    CONSTRAINT chk_sredstvo_status
        CHECK (status IN ('u izradi', 'aktivno', 'rashodovano', 'otpisano')),

    trenutna_vrijednost NUMBER(15,2) NOT NULL,
    CONSTRAINT chk_trenutna_vrijednost_nonneg
        CHECK (trenutna_vrijednost >= 0),

    nabavna_vrijednost NUMBER(15,2) NOT NULL,
    CONSTRAINT chk_nabavna_vrijednost_nonneg
        CHECK (nabavna_vrijednost >= 0),

    godisnji_iznos_amortizacije NUMBER(15,2) DEFAULT 0 NOT NULL,
    ukupni_iznos_amortizacija NUMBER(15,2) DEFAULT 0 NOT NULL,

    datum_amortizacije DATE,

    am_grupa NUMBER NOT NULL,

    CONSTRAINT fk_sredstvo_am_grupa
        FOREIGN KEY (am_grupa)
        REFERENCES amortizacijska_grupa(id)
);

CREATE INDEX idx_sredstvo_am_grupa ON sredstvo (am_grupa);
